### PR TITLE
Update sv.po

### PR DESCRIPTION
**Pull request by eson57**
Here's the updated Swedish translation.
I did not try to make it work yet but PoEdit, which I use for translation, complained about "duplicate message definition" on 7 strings.
I'll try to build with it later, when I'm not short of time.

### CODE REVIEW

**Comment by eson57** [comment]
Had to fix the "duplicate message definition" to be able to build flatpak, but translation still don't work.

**Comment by ADBeveridge** [comment]
Yes, there was some more typos. I fixed them but I have not committed the changes. When I do, I'll take care of the discrepancy between them

**Comment by ADBeveridge** [comment]
Because of all my UI rework and renaming of options, I deleted your `sv.po` file and created a new swedish one from my `es.po` in POEdit. I filled in the translations using Dialect, which is a flatpak that uses Google Translate for translation. Can you look at it and fix (possible) strange and incorrect situation word use? GT isn't perfect in this. Thanks a lot! :)

**Comment by eson57** [comment]
GT is terrible for Swedish. Instead you should use Microsoft Translate or DeepL.

**Pull request merged**
