### PR TITLE
Add initial Dutch translation

### PR DESCRIPTION
**Pull request by flipflop97**
Translate everything to Dutch except metainfo and gschema (I will probably do these later).

Note that I was not able to re-generate the `.pot` file, the `POTFILES` file will probably need to be updated.

### CODE REVIEW

**Comment by ADBeveridge** [comment]
I'll merge the pr when the metainfo file is translated. Regarding the POT file, I posted a command for translators to use to update the POT file. See [here](https://github.com/ADBeveridge/raider/tree/develop/po). Thank you!

**Comment by flipflop97** [comment]
> Regarding the POT file, I posted a command for translators to use to update the POT file. See [here](https://github.com/ADBeveridge/raider/tree/develop/po). Thank you!

I tried doing that, but it showed me an error message. After looking better I found that `src/raider-shortcuts.ui` will need to be renamed to `src/raider-shortcuts.blp`. Do you want me to do that here, in another MR, or do it yourself?

> I'll merge the pr when the metainfo file is translated.

I thought I'd submit it already since the changelog (I already translated the name/description in the metainfo) and gschema are usually seen as low priority, but I'll try to finish the translation later.

**Comment by ADBeveridge** [comment]
If you're fine with doing converting it to blp, go ahead :)

**Comment by ADBeveridge** [comment]
I have a little free time, I'll do it for you now

**Comment by ADBeveridge** [comment]
I'll go ahead and merge, you can send the gsettings + gschema later

**Comment by flipflop97** [comment]
Thanks! I'll try to add them soon

**Pull request merged**
