### PR TITLE
Adwaita-1.4 Dependency

### PR DESCRIPTION
**Pull request by Spice-Weasel**
Hi,
I have successfully built and run the application manually on Ubuntu 22.04. I have added libadwaita version >=1.4.0 as a dependency, with a fallback to a subproject where that revision is cloned from the project gitlab. 

This was taken from here:
https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/build-howto.html

In order to get this to work successfully, I had to copy across a newer version of Adw-1.typelib as the version that ships with Ubuntu 22.04 does not include the more recent types included with libadwaita 1.4.0 and later. I have not included this typelib file in the PR and am unsure if there is a better way to do this.

I have not yet included the additional dependencies required for the build process - I will do a fresh 22.04 install in a VM and document it all.

### CODE REVIEW

**Comment by ADBeveridge** [comment]
I'll look at them when I get home. Thanks so much 🙏

**Comment by Spice-Weasel** [comment]
Sorry, it's a draft - but I realise the commit log is still a mess.

**Comment by ADBeveridge** [comment]
Thats fine, don't worry.

**Comment by ADBeveridge** [comment]
Let me know when you are ready to unmark this as Draft. Thanks!

**Comment by Spice-Weasel** [comment]
Do you want documentation as part of this pr?

**Comment by ADBeveridge** [comment]
Yes. I tried building your version of the build in a brand-new image container (toolbox) on Fedora, and it gave me errors about cairo-xlib, so documentation is definitely a must. You only have to do your current distro. I'll look at the doc and apply it to other distros like arch, fedora, and debian.

**Comment by Spice-Weasel** [comment]
Hey, I've updated the documentation and have been busy failing the markdown format checks! :dancers:

**Comment by ADBeveridge** [comment]
😁 alright. I'm at work right now, so I'll take a look later.

**Comment by Spice-Weasel** [comment]
Hi sorry if this is a silly question - do you need me to fix the issues flagged with the Markdown? I don't see any visual difference between what I have done and what already exists in the README

**Comment by ADBeveridge** [comment]
Lol no. As long as it renders correctly on GitHub, go for it.

**Comment by Spice-Weasel** [comment]
It's fine then, I've documented it for a fresh gnome box Ubuntu 22.04 install! ☺️

**Comment by Spice-Weasel** [comment]
Let me know if you want me to resubmit this with a clean commit history, run some tests on Fedora and Arch - or just leave it for now. I rebased to squash some of the commits together xD

**Comment by ADBeveridge** [comment]
I need to get around to this lol. I'll handle the rest, don't worry.  It should be merged within 8 hrs.

**Comment by ADBeveridge** [comment]
Merged! Sorry i forgot again.

**Comment by Spice-Weasel** [comment]
Thanks, I'm sorry for my lousy commit history. I'll do better next time

**Pull request merged**
