### PR TITLE
Slovenian translation

### PR DESCRIPTION
**Pull request by MatejKovacic**

### CODE REVIEW

**Comment by ADBeveridge** [comment]
Thank you @MatejKovacic!

**Comment by ADBeveridge** [comment]
Also, I accidentally clicked merge, but please open another PR that adds the slovenian translation to the LINGUAS file. Otherwise your translation wont show up, afaik.

**Comment by MatejKovacic** [comment]
I did that. Just a quick question... how often are Flatpak packages build (meaning: when my translation will appear on my system)?

**Comment by ADBeveridge** [comment]
Only when I release a new version. I will probably release a new patch update (2.1.1, bumping up from 2.1.0) within the next week or so.

**Comment by MatejKovacic** [comment]
Sorry, just asking... have you managed to prepare a new release yet?

**Comment by ADBeveridge** [comment]
Yeah, sorry. I've been a bit busy, and haven't got around to it. I'll do it soon though.

**Comment by MatejKovacic** [comment]
Sorry, but I still do not see the Slovenian translation. I have version 3.0.1 in Ubuntu. Is LINGUAS file OK?

**Comment by ADBeveridge** [comment]
try renaming it to just sl.po

**Comment by ADBeveridge** [comment]
but not sure what's happening. lmk how the above goes

**Comment by MatejKovacic** [comment]
OK, I created new pull request.

**Pull request merged**
